# Generated by Django 5.2.2 on 2025-06-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FCMTokenModel",
        ),
    ]
