# Generated by Django 5.2.2 on 2025-06-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_delete_fcmtokenmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='files_attachment',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='files_attachment',
            field=models.ManyToManyField(to='chat_app.chatattachmentmodel'),
        ),
    ]
