# Generated by Django 5.2.2 on 2025-06-19 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_remove_messagemodel_files_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ('sent_at',)},
        ),
        migrations.AddIndex(
            model_name='messagemodel',
            index=models.Index(fields=['chat'], name='chat_app_me_chat_id_43a1d5_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemodel',
            index=models.Index(fields=['sender'], name='chat_app_me_sender__dbd61d_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemodel',
            index=models.Index(fields=['sent_at'], name='chat_app_me_sent_at_1de66d_idx'),
        ),
    ]
