# Generated by Django 5.2.2 on 2025-07-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_chatmodel_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='group_icon',
            field=models.ImageField(blank=True, null=True, upload_to='group_icons/'),
        ),
    ]
