# Generated by Django 5.2.2 on 2025-07-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_chatmodel_admins_chatmodel_deleted_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('mention', 'Mention'), ('document', 'Document'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
