# Generated by Django 5.2.2 on 2025-07-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_messagemodel_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('mention', 'Mention'), ('document', 'Document'), ('image', 'Image'), ('file', 'File')], default='text', max_length=10),
        ),
    ]
