# Generated by Django 5.2.2 on 2025-07-04 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_chatmodel_group_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='deleted_for',
            field=models.ManyToManyField(blank=True, related_name='deleted_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
