# Generated by Django 5.2.2 on 2025-06-15 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("follower_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_follow_notifications", models.BooleanField(default=True)),
                ("enable_like_notifications", models.BooleanField(default=True)),
                ("enable_comment_notifications", models.BooleanField(default=True)),
                ("enable_mention_notifications", models.BooleanField(default=True)),
                ("enable_system_notifications", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("push_notifications", models.BooleanField(default=True)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="firebasenotification",
            name="action_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="firebasenotification",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="firebasenotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("follow", "Follow"),
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("mention", "Mention"),
                    ("system", "System"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="firebasenotification",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="follower",
            name="is_muted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="firebasenotification",
            index=models.Index(
                fields=["user", "is_read"], name="follower_ap_user_id_17b9cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="firebasenotification",
            index=models.Index(
                fields=["user", "created_at"], name="follower_ap_user_id_839e69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="firebasenotification",
            index=models.Index(
                fields=["notification_type"], name="follower_ap_notific_1e3d29_idx"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
