# Generated by Django 5.2.2 on 2025-06-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("follower_app", "0002_notificationpreference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="follower",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="follower",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
