# Generated by Django 5.2.2 on 2025-06-09 10:47

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import user_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('helper_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('user', 'User'), ('vendor', 'Vendor')], max_length=10)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, unique=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helper_app.citiesmodel')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helper_app.countrymodel')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helper_app.statesmodel')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', user_app.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_requested_at', models.DateTimeField(blank=True, null=True)),
                ('profile_pictureee', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('profile_link', models.URLField(blank=True, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='user_app.maincategorymodel')),
            ],
            options={
                'unique_together': {('name', 'main_category')},
            },
        ),
        migrations.CreateModel(
            name='VendorProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pan_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('aadhar_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('gst_number', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('pan_document', models.FileField(blank=True, null=True, upload_to='vendor_docs/pan/')),
                ('aadhar_document', models.FileField(blank=True, null=True, upload_to='vendor_docs/aadhar/')),
                ('gst_document', models.FileField(blank=True, null=True, upload_to='vendor_docs/gst/')),
                ('company_registration', models.FileField(blank=True, null=True, upload_to='vendor_docs/company_reg/')),
                ('msme_certificate', models.FileField(blank=True, null=True, upload_to='vendor_docs/msme/')),
                ('achievement_awards', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('business_presence', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendor_docs/logo/')),
                ('perma_link', models.URLField(blank=True, null=True)),
                ('store_owner', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('locked', 'Locked')], db_index=True, default='published', max_length=20)),
                ('vendor_status', models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('rejected', 'Rejected')], db_index=True, default='unverified', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_categories', models.ManyToManyField(related_name='vendors_main_categories', to='user_app.maincategorymodel')),
                ('subcategories', models.ManyToManyField(related_name='vendors_subcategories', to='user_app.subcategorymodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['business_name'], name='user_app_ve_busines_6308bf_idx'), models.Index(fields=['pan_number'], name='user_app_ve_pan_num_fbd7d0_idx'), models.Index(fields=['aadhar_number'], name='user_app_ve_aadhar__0667b8_idx'), models.Index(fields=['gst_number'], name='user_app_ve_gst_num_686f30_idx'), models.Index(fields=['store_owner'], name='user_app_ve_store_o_76dc87_idx'), models.Index(fields=['status'], name='user_app_ve_status_049cc6_idx'), models.Index(fields=['vendor_status'], name='user_app_ve_vendor__ee6262_idx'), models.Index(fields=['created_at'], name='user_app_ve_created_20f2ab_idx')],
            },
        ),
    ]
