# Generated by Django 5.2.2 on 2025-06-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='profile_pictureee',
            new_name='profile_picture',
        ),
    ]
