# Generated by Django 5.2.2 on 2025-06-10 10:16

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_profile_pictureee_profilemodel_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, unique=True),
        ),
    ]
