# Generated by Django 5.2.2 on 2025-06-15 06:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0005_alter_profilemodel_bio_profileexternallinkmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="FCMTokenModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("android", "android"),
                            ("ios", "ios"),
                            ("web", "web"),
                            ("desktop", "desktop"),
                            ("other", "other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("token", models.TextField()),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
