# Generated by Django 5.2.2 on 2025-06-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0006_fcmtokenmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fcmtokenmodel",
            old_name="employee",
            new_name="user",
        ),
    ]
