# Generated by Django 5.2.2 on 2025-06-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0007_rename_employee_fcmtokenmodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcmtokenmodel",
            name="device_name",
            field=models.CharField(default="Unknown Device", max_length=255),
        ),
    ]
