# Generated by Django 5.2.2 on 2025-06-18 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_fcmtokenmodel_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileexternallinkmodel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='user_app.profilemodel'),
        ),
    ]
