# Generated by Django 5.2.2 on 2025-06-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_alter_profileexternallinkmodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofilemodel',
            name='vendor_banner',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_banner/banners/'),
        ),
    ]
