# Generated by Django 5.2.2 on 2025-06-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_vendorprofilemodel_vendor_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategorymodel',
            name='main_category_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_category_image/'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='sub_category_image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_category_image/'),
        ),
    ]
