# Generated by Django 5.2.2 on 2025-06-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_maincategorymodel_main_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
