# Generated by Django 5.2.2 on 2025-07-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_usermodel_is_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategorymodel',
            options={'ordering': ['sequence', 'name']},
        ),
        migrations.AlterModelOptions(
            name='subcategorymodel',
            options={'ordering': ['main_category', 'sequence', 'name']},
        ),
        migrations.AddField(
            model_name='maincategorymodel',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=1, help_text='Display order'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=1, help_text='Display order within main category'),
        ),
    ]
