# Generated by Django 5.2.2 on 2025-06-08 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('country_code', models.CharField(max_length=3, verbose_name='country code')),
                ('currency', models.CharField(max_length=3)),
                ('calling_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='StatesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper_app.countrymodel')),
            ],
        ),
        migrations.CreateModel(
            name='CitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper_app.countrymodel')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper_app.statesmodel')),
            ],
        ),
    ]
