# Generated by Django 5.2.2 on 2025-06-19 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0002_inquirymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquirymodel',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='inquirymodel',
            old_name='person_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='inquirymodel',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='inquirymodel',
            old_name='message',
            new_name='subject',
        ),
    ]
