# Generated by Django 5.2.2 on 2025-06-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0005_tag_post_tags_reel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
