# Generated by Django 5.2.2 on 2025-06-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_post_slug_reel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
