# Generated by Django 5.2.2 on 2025-06-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0009_like_is_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
    ]
