# Generated by Django 5.2.2 on 2025-07-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0013_story_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='thumbnail',
        ),
    ]
