# Generated by Django 5.2.2 on 2025-07-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0014_remove_story_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightmodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='highlights/covers/'),
        ),
    ]
