# Generated by Django 5.2.2 on 2025-07-12 05:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0016_mentionmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentionmodel',
            unique_together={('mentioned_user', 'object_id')},
        ),
        migrations.RemoveField(
            model_name='mentionmodel',
            name='content_type',
        ),
    ]
