# Generated by Django 5.2.2 on 2025-07-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0017_alter_mentionmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentionmodel',
            old_name='actor',
            new_name='creator',
        ),
    ]
