# Generated by Django 5.2.2 on 2025-07-12 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('post_app', '0018_rename_actor_mentionmodel_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentionmodel',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
