# Generated by Django 5.2.2 on 2025-07-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0020_story_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='mention_user_data',
            field=models.CharField(blank=True),
        ),
    ]
